version: '3.2'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: NazareTedesco90
      MYSQL_DATABASE: huehuebr
    ports:
      - "3306:3306"
  backend:
    build: backend
    working_dir: /home/docker/code/app/hue
    command: bash -c " python3 manage.py collectstatic --noinput && python3 manage.py migrate && supervisord -n"
    volumes:
      - type: 'bind'
        source: ./backend/app
        target: /home/docker/code/app
    ports:
      - "80:80"
      - "8000:8000"
    depends_on:
      - db